services:
  - type: web
    name: leg-training
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: node server-static.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
